clear;

dir_data = './SimulatedData/IXI';
Nii      = nifti(spm_select('FPList',dir_data,'^.*\.nii$'));

VoxelSize           = 1;
Verbose             = 2;
WorkersParfor       = Inf;

IterMax             = 20;

ADMMStepSize        = 0;
RegScaleSuperResMRI = 5;
DecreasingReg       = true;
CoRegister          = false;
IterImage           = 3;

%% ------------------------------
EstimateRigid   = true;
OutputDirectory = './Output/EstimateRigid/True';

spm_mtv_preproc('InputImages',Nii,'Method','superres', ...
                'VoxelSize',VoxelSize,'Verbose',Verbose, ...
                'RegScaleSuperResMRI',RegScaleSuperResMRI, ...                
                'ADMMStepSize',ADMMStepSize,'WorkersParfor',WorkersParfor, ...
                'IterMax',IterMax, ...
                'DecreasingReg',DecreasingReg,'CoRegister',CoRegister, ...
                'EstimateRigid',EstimateRigid,'IterImage',IterImage, ...
                'OutputDirectory',OutputDirectory);
            
%% ------------------------------
EstimateRigid   = false;
OutputDirectory = './Output/EstimateRigid/False';

spm_mtv_preproc('InputImages',Nii,'Method','superres', ...
                'VoxelSize',VoxelSize,'Verbose',Verbose, ...
                'RegScaleSuperResMRI',RegScaleSuperResMRI, ...                
                'ADMMStepSize',ADMMStepSize,'WorkersParfor',WorkersParfor, ...
                'IterMax',IterMax, ...
                'DecreasingReg',DecreasingReg,'CoRegister',CoRegister, ...
                'EstimateRigid',EstimateRigid,'IterImage',IterImage, ...
                'OutputDirectory',OutputDirectory);            